name: Pantheon Build
on:
  push:
    branches:
      - master

jobs:
  github_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pantheon Deploy
      uses: pantheoncarl/pantheon-deploy@main
      id: cache-vendor
      env:
        PANTHEONSITEUUID: d232a51c-bff3-4671-bdaa-fba529998d05
        PANTHEON_TERMINUS_MACHINE_TOKEN: ${{ secrets.PANTHEON_TERMINUS_MACHINE_TOKEN }}
        PANTHEON_PRIVATE_KEY: ${{ secrets.PANTHEON_PRIVATE_KEY }}
        REMOTE_PATH: "wp-content/themes/framenet"